stages:
  - build
  - deploy

.variables_template: &variables_definition
  variables:
    BASE_NAME: "edje2yuv"
    PKG_CONFIG_PATH: "/opt/lv2/lib/pkgconfig:/opt/${CI_BUILD_NAME}/lib/pkgconfig:/usr/lib/${CI_BUILD_NAME}/pkgconfig"

.common_template: &common_definition
  <<: *variables_definition
  stage: build
  artifacts:
    name: "${BASE_NAME}-$(cat VERSION)-${CI_BUILD_NAME}"
    paths:
      - "${BASE_NAME}-$(cat VERSION)/"

.build_template: &build_definition
  <<: *common_definition
  script:
    - meson --prefix=/ --cross-file "${CI_BUILD_NAME}" -Dstatic-build=false build
    - ninja -C build
    - DESTDIR="${CI_PROJECT_DIR}/${BASE_NAME}-$(cat VERSION)/${CI_BUILD_NAME}" ninja -C build install

.universal_linux_template: &universal_linux_definition
  image: ventosus/universal-linux-gnu
  <<: *build_definition

.arm_linux_template: &arm_linux_definition
  image: ventosus/arm-linux-gnueabihf
  <<: *build_definition

# building in docker
x86_64-linux-gnu:
  before_script:
    - apt-get update
    - apt-get install -y libefl-all-dev libmjpegtools-dev libswscale-dev
  <<: *universal_linux_definition

i686-linux-gnu:
  before_script:
    - apt-get update
    - apt-get install -y libefl-all-dev:i386 libmjpegtools-dev:i386 libswscale-dev:i386
  <<: *universal_linux_definition

arm-linux-gnueabihf:
  before_script:
    - apt-get update
    - apt-get install -y libefl-all-dev:armhf libmjpegtools-dev:armhf libswscale-dev:armhf
  <<: *arm_linux_definition

aarch64-linux-gnu:
  before_script:
    - apt-get update
    - apt-get install -y libefl-all-dev:arm64 libmjpegtools-dev:arm64 libswscale-dev:arm64
  <<: *arm_linux_definition

pack:
  <<: *variables_definition
  stage: deploy
  script:
    - echo 'packing up...'
  artifacts:
    name: "${BASE_NAME}-$(cat VERSION)"
    paths:
      - "${BASE_NAME}-$(cat VERSION)/"
