language: c
os: linux
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository -y ppa:enlightenment-git/ppa
 - sudo apt-get -q update
install:
 - sudo apt-get install -y libefl-dev libswscale-dev libmjpegtools-dev
before_script:
 - mkdir build && pushd build && cmake .. && popd
script:
 - pushd build && make && sudo make install && popd
